<Project ToolsVersion="4.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
	<ItemGroup>
		<Library Include="MongoDB.Driver"/>
		<Library Include="MongoDB.Bson"/>
		<Library Include="Qorpent.Integration.MongoDB"/>
		<Config Include="..\qorpent.integration\qi-mongo.ioc-manifest.bxl" />  
	</ItemGroup>
	<Import Project="..\qorpent.kernel\package-install.targets" />	
</Project>