<Project ToolsVersion="4.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
	<ItemGroup>
		<Library Include="TidyManaged"/>
		<Library Include="libtidy"/>
		<Library Include="Qorpent.Integration.Tidy"/>
		<Config Include="..\qorpent.integration\qi-tidy.ioc-manifest.bxl" />  
	</ItemGroup>
	<Import Project="..\qorpent.kernel\package-install.targets" />
</Project>